# Permalinks
permalink:           pretty

# Setup
title:               piitime
tagline:             'Looking at time'
description:         'Taking a look at interesting things that happened throughout time.'
url:                 http://pii.space
baseurl:             '/piitime'
future:              true
paginate: 5
plugins: ['jekyll-paginate']


# About/contact
author:
  name:              pii
  url:               ''
  email:             ''

# Custom vars
version:             1.0.0

#lsi: false
#safe: true
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
